name: good_dream
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.10+11

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^3.0.3+2
  provider: ^4.3.2+2
  numberpicker: ^1.2.1
  fluttertoast: ^7.1.1
  flare_splash_screen: ^2.0.1+2
  shimmer: ^1.1.2
  url_launcher: ^6.0.2
  firebase_core: ^1.0.2
  firebase_analytics: ^7.1.1
  firebase_crashlytics: ^1.0.0
  admob_flutter: ^1.0.1
  flex_color_scheme: ^2.1.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
       - assets/wind_w.png
       - assets/wind_on.png
       - assets/bonfire2_w.png
       - assets/bonfire2_on.png
       - assets/jungle_w.png
       - assets/jungle_on.png
       - assets/piano_w.png
       - assets/piano_on.png
       - assets/piano2_w.png
       - assets/piano2_on.png
       - assets/piano3_w.png
       - assets/piano3_on.png
       - assets/piano4_w.png
       - assets/piano4_on.png
       - assets/piano5_w.png
       - assets/piano5_on.png
       - assets/piano6_w.png
       - assets/piano6_on.png
       - assets/jungle_w.png
       - assets/bird2_w.png
       - assets/bird2_on.png
       - assets/cricket_w.png
       - assets/cricket_on.png
       - assets/forest_w.png
       - assets/forest_on.png
       - assets/plane_w.png
       - assets/plane_on.png
       - assets/tent_on.png
       - assets/tent_w.png
       - assets/train_on.png
       - assets/train_w.png
       - assets/rain_w.png
       - assets/rain_on.png
       - assets/river_w.png
       - assets/river_on.png
       - assets/washing_machine_w.png
       - assets/washing_machine_on.png
       - assets/jacuzzi_w.png
       - assets/jacuzzi_on.png
       - assets/thunder_w.png
       - assets/thunder_on.png
       - assets/air_conditioner_on.png
       - assets/air_conditioner_w.png
       - assets/coming-soon.png
       - assets/icons/dream_light.png
       - assets/bus_w.png
       - assets/bus_on.png
       - assets/water_drop_w.png
       - assets/water_drop_on.png
       - assets/guitar_w.png
       - assets/guitar_on.png
       - assets/binaural_w.png
       - assets/binaural_on.png
       - assets/vacuum_cleaner_w.png
       - assets/vacuum_cleaner_on.png
       - assets/hair_dryer_w.png
       - assets/hair_dryer_on.png
       - assets/flute_w.png
       - assets/flute_on.png
       - assets/keyboard_w.png
       - assets/keyboard_on.png
       - assets/frog_w.png
       - assets/frog_on.png
       - assets/woodpecker_w.png
       - assets/woodpecker_on.png
       - assets/stork_w.png
       - assets/stork_on.png
       - assets/lotus_w.png
       - assets/lotus_on.png
       - assets/zen_w.png
       - assets/zen_on.png
       - assets/audio/
       - assets/splash.flr
       - assets/intro.flr
       - assets/intro2.flr

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
