import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:good_dream/models/view_models.dart';

List<ViewModels> get models => arrays;
final arrays = [
  ViewModels(
      disableIcon: 'assets/images/woodpecker_w.png',
      enableIcon: 'assets/images/woodpecker_on.png',
      iconTitleText: 'Woodpecker',
      audioFile: "assets/audio/woodpecker.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/frog_w.png',
      enableIcon: 'assets/images/frog_on.png',
      iconTitleText: 'Frogs ambience',
      audioFile: "assets/audio/frogs_ambience.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/stork_w.png',
      enableIcon: 'assets/images/stork_on.png',
      iconTitleText: 'Stork',
      audioFile: "assets/audio/storks.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/city_park_w.png',
      enableIcon: 'assets/images/city_park_on.png',
      iconTitleText: 'City park',
      audioFile: "assets/audio/city_park.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/fireplace_w.png',
      enableIcon: 'assets/images/fireplace_on.png',
      iconTitleText: 'Fireplace',
      audioFile: "assets/audio/fireplace.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/bonfire2_w.png',
      enableIcon: 'assets/images/bonfire2_on.png',
      iconTitleText: 'Bonfire',
      audioFile: "assets/audio/bonfire.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      volumeControlSlider: 0.5,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/bird2_w.png',
      enableIcon: 'assets/images/bird2_on.png',
      iconTitleText: 'Bird',
      audioFile: "assets/audio/bird.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/thunder_w.png',
      enableIcon: 'assets/images/thunder_on.png',
      iconTitleText: 'Thunder',
      audioFile: "assets/audio/thunder_ambience.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/cricket_w.png',
      enableIcon: 'assets/images/cricket_on.png',
      iconTitleText: 'Cricket',
      audioFile: "assets/audio/cricket.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/forest_w.png',
      enableIcon: 'assets/images/forest_on.png',
      iconTitleText: 'Forest',
      audioFile: "assets/audio/forest_ambience.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/wind_w.png',
      enableIcon: 'assets/images/wind_on.png',
      iconTitleText: 'Wind',
      audioFile: "assets/audio/wind.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/jungle_w.png',
      enableIcon: 'assets/images/jungle_on.png',
      iconTitleText: 'Tropical',
      audioFile: "assets/audio/tropical_ambience.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
];

List<ViewModels> get models2 => arrays2;
final arrays2 = [
  ViewModels(
      disableIcon: 'assets/images/river_w.png',
      enableIcon: 'assets/images/river_on.png',
      iconTitleText: 'River',
      audioFile: "assets/audio/river.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/creek_w.png',
      enableIcon: 'assets/images/creek_on.png',
      iconTitleText: 'Small creek',
      audioFile: "assets/audio/small_creek.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/rain_w.png',
      enableIcon: 'assets/images/rain_on.png',
      iconTitleText: 'Rain',
      audioFile: "assets/audio/rain.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/rain_on_car_roof_w.png',
      enableIcon: 'assets/images/rain_on_car_roof_on.png',
      iconTitleText: 'Rain on car roof',
      audioFile: "assets/audio/rain_on_car_roof.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/windshield_w.png',
      enableIcon: 'assets/images/windshield_on.png',
      iconTitleText: 'Rain on car windows',
      audioFile: "assets/audio/windshield_wipers.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/fountain_park_w.png',
      enableIcon: 'assets/images/fountain_park_on.png',
      iconTitleText: 'Fountain in park',
      audioFile: "assets/audio/fountain_park.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/raincoat_w.png',
      enableIcon: 'assets/images/raincoat_on.png',
      iconTitleText: 'Rain under raincoat',
      audioFile: "assets/audio/rain_under_raincoat.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/rain_windows_w.png',
      enableIcon: 'assets/images/rain_windows_on.png',
      iconTitleText: 'Rain on windows',
      audioFile: 'assets/audio/rain_on_windows.ogg',
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/sea_w.png',
      enableIcon: 'assets/images/sea_on.png',
      iconTitleText: 'Sea',
      audioFile: 'assets/audio/sea.ogg',
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/cave_w.png',
      enableIcon: 'assets/images/cave_on.png',
      iconTitleText: 'Cave',
      audioFile: 'assets/audio/amb_cave.ogg',
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/waterfall_w.png',
      enableIcon: 'assets/images/waterfall_on.png',
      iconTitleText: 'Waterfall',
      audioFile: "assets/audio/waterfall.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/jacuzzi_w.png',
      enableIcon: 'assets/images/jacuzzi_on.png',
      iconTitleText: 'Jacuzzi',
      audioFile: "assets/audio/jacuzzi.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
];
