import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:good_dream/models/ViewModels.dart';

List<ViewModels> get models => arrays;
final arrays = [
  ViewModels(
      events: 'click_woodpecker',
      picOff: 'assets/images/woodpecker_w.png',
      picOn: 'assets/images/woodpecker_on.png',
      title: 'Woodpecker',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/woodpecker.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_frogs_ambience',
      picOff: 'assets/images/frog_w.png',
      picOn: 'assets/images/frog_on.png',
      title: 'Frogs ambience',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/frogs_ambience.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_storks',
      picOff: 'assets/images/stork_w.png',
      picOn: 'assets/images/stork_on.png',
      title: 'Stork',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/storks.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_city_park',
      picOff: 'assets/images/city_park_w.png',
      picOn: 'assets/images/city_park_on.png',
      title: 'City park',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/city_park.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_fireplace',
      picOff: 'assets/images/fireplace_w.png',
      picOn: 'assets/images/fireplace_on.png',
      title: 'Fireplace',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/fireplace.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_bonfire',
      picOff: 'assets/images/bonfire2_w.png',
      picOn: 'assets/images/bonfire2_on.png',
      title: 'Bonfire',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/bonfire.ogg",
      vol: 0.5,
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_bird',
      picOff: 'assets/images/bird2_w.png',
      picOn: 'assets/images/bird2_on.png',
      title: 'Bird',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/bird.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_thunder',
      picOff: 'assets/images/thunder_w.png',
      picOn: 'assets/images/thunder_on.png',
      title: 'Thunder',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/thunder_ambience.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_cricket',
      picOff: 'assets/images/cricket_w.png',
      picOn: 'assets/images/cricket_on.png',
      title: 'Cricket',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/cricket.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_forest',
      picOff: 'assets/images/forest_w.png',
      picOn: 'assets/images/forest_on.png',
      title: 'Forest',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/forest_ambience.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_wind',
      picOff: 'assets/images/wind_w.png',
      picOn: 'assets/images/wind_on.png',
      title: 'Wind',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/wind.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_jungle',
      picOff: 'assets/images/jungle_w.png',
      picOn: 'assets/images/jungle_on.png',
      title: 'Tropical',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/tropical_ambience.ogg",
      player: AssetsAudioPlayer()),
];

List<ViewModels> get models2 => arrays2;
final arrays2 =[
  ViewModels(
      events: 'click_river',
      picOff: 'assets/images/river_w.png',
      picOn: 'assets/images/river_on.png',
      title: 'River',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/river.ogg",
      player: AssetsAudioPlayer()),

  ViewModels(
      events: 'click_small_creek',
      picOff: 'assets/images/creek_w.png',
      picOn: 'assets/images/creek_on.png',
      title: 'Small creek',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/small_creek.ogg",
      player: AssetsAudioPlayer()),

  ViewModels(
      events: 'click_rain',
      picOff: 'assets/images/rain_w.png',
      picOn: 'assets/images/rain_on.png',
      title: 'Rain',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/rain.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_rain_on_car_roof',
      picOff: 'assets/images/rain_on_car_roof_w.png',
      picOn: 'assets/images/rain_on_car_roof_on.png',
      title: 'Rain on car roof',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/rain_on_car_roof.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_rain_on_car_windows',
      picOff: 'assets/images/windshield_w.png',
      picOn: 'assets/images/windshield_on.png',
      title: 'Rain on car windows',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/windshield_wipers.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_fountain_park',
      picOff: 'assets/images/fountain_park_w.png',
      picOn: 'assets/images/fountain_park_on.png',
      title: 'Fountain in park',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/fountain_park.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_rain_under_raincoat',
      picOff: 'assets/images/raincoat_w.png',
      picOn: 'assets/images/raincoat_on.png',
      title: 'Rain under raincoat',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/rain_under_raincoat.ogg",
      player: AssetsAudioPlayer()),

  ViewModels(
      events: 'click_rain_on_windows',
      picOff: 'assets/images/rain_windows_w.png',
      picOn: 'assets/images/rain_windows_on.png',
      title: 'Rain on windows',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: 'assets/audio/rain_on_windows.ogg',
      player: AssetsAudioPlayer()),

  ViewModels(
      events: 'click_sea',
      picOff: 'assets/images/sea_w.png',
      picOn: 'assets/images/sea_on.png',
      title: 'Sea',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: 'assets/audio/sea.ogg',
      player: AssetsAudioPlayer()),

  ViewModels(
      events: 'click_cave',
      picOff: 'assets/images/cave_w.png',
      picOn: 'assets/images/cave_on.png',
      title: 'Cave',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: 'assets/audio/amb_cave.ogg',
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_waterfall',
      picOff: 'assets/images/waterfall_w.png',
      picOn: 'assets/images/waterfall_on.png',
      title: 'Waterfall',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/waterfall.ogg",
      player: AssetsAudioPlayer()),

  ViewModels(
      events: 'click_jacuzzi',
      picOff: 'assets/images/jacuzzi_w.png',
      picOn: 'assets/images/jacuzzi_on.png',
      title: 'Jacuzzi',
      isFav: false,
      sounds: "assets/audio/jacuzzi.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),

];






