import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:good_dream/models/ViewModels.dart';

List<ViewModels> get models3 => arrays3;
final arrays3 = [

  ViewModels(
      events: 'click_the_meditations.',
      picOff: 'assets/images/lotus_w.png',
      picOn: 'assets/images/lotus_on.png',
      title: 'Meditation',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/flowing_river2.ogg",
      player: AssetsAudioPlayer()),

  ViewModels(
      events: 'click_healing_meditation',
      picOff: 'assets/images/healing_w.png',
      picOn: 'assets/images/healing_on.png',
      title: 'Healing meditation',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/healing_meditation.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_yoga',
      picOff: 'assets/images/yoga_w.png',
      picOn: 'assets/images/yoga_on.png',
      title: 'Yoga',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/morning_sun.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_asian_piano',
      picOff: 'assets/images/piano3_w.png',
      picOn: 'assets/images/piano3_on.png',
      title: 'Asian piano',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/asian_piano.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_piano',
      picOff: 'assets/images/piano6_w.png',
      picOn: 'assets/images/piano6_on.png',
      title: 'Piano',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/love_piano.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_background_piano ',
      picOff: 'assets/images/piano5_w.png',
      picOn: 'assets/images/piano5_on.png',
      title: 'Background Piano ',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/background_piano.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_binaural',
      picOff: 'assets/images/binaural_w.png',
      picOn: 'assets/images/binaural_on.png',
      title: 'Binaural',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/binaural.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_guitar',
      picOff: 'assets/images/guitar_w.png',
      picOn: 'assets/images/guitar_on.png',
      title: 'Guitar Song',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/ambient_guitars.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_background_guitar',
      picOff: 'assets/images/guitar_w.png',
      picOn: 'assets/images/guitar_on.png',
      title: 'Background Guitar',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/background_guitar.ogg",
      player: AssetsAudioPlayer()),


  ViewModels(
      events: 'click_om',
      picOff: 'assets/images/om_w.png',
      picOn: 'assets/images/om_on.png',
      title: 'Om surrounding',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/om.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_zen',
      picOff: 'assets/images/zen_w.png',
      picOn: 'assets/images/zen_on.png',
      title: 'Zen',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/zen.ogg",
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_flute',
      picOff: 'assets/images/flute_w.png',
      picOn: 'assets/images/flute_on.png',
      title: 'Flute',
      isFav: false,
      opacityOff: 0.0,
      opacityOn: 1.0,
      sounds: "assets/audio/flute.ogg",
      player: AssetsAudioPlayer()),
];

List<ViewModels> get models4 => arrays4;
final arrays4 = [
  ViewModels(
      checkThemeMode: null,
      events: 'click_plane',
      picOff: 'assets/images/plane_w.png',
      picOn: 'assets/images/plane_on.png',
      title: 'Plane',
      isFav: false,
      sounds: "assets/audio/plane.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_train',
      picOff: 'assets/images/train_w.png',
      picOn: 'assets/images/train_on.png',
      title: 'Train',
      isFav: false,
      sounds: "assets/audio/train.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_car_driving',
      picOff: 'assets/images/car_w.png',
      picOn: 'assets/images/car_on.png',
      title: 'Car Driving',
      isFav: false,
      sounds: "assets/audio/car_driving.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_bus',
      picOff: 'assets/images/bus_w.png',
      picOn: 'assets/images/bus_on.png',
      title: 'Bus',
      isFav: false,
      sounds: "assets/audio/fast_bus.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_washing_machine',
      picOff: 'assets/images/washing_machine_w.png',
      picOn: 'assets/images/washing_machine_on.png',
      title: 'Washing machine',
      isFav: false,
      sounds: "assets/audio/washing_machine.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_conditioner',
      picOff: 'assets/images/air_conditioner_w.png',
      picOn: 'assets/images/air_conditioner_on.png',
      title: 'Air Conditioner',
      isFav: false,
      sounds: "assets/audio/air_conditioner2.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_vacuum_cleaner',
      picOff: 'assets/images/vacuum_cleaner_w.png',
      picOn: 'assets/images/vacuum_cleaner_on.png',
      title: 'Vacuum cleaner',
      isFav: false,
      sounds: "assets/audio/vacuum_cleaner2.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_hair_dryer',
      picOff: 'assets/images/hair_dryer_w.png',
      picOn: 'assets/images/hair_dryer_on.png',
      title: 'Hair dryer',
      isFav: false,
      sounds: "assets/audio/hair_dryer2.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),
  ViewModels(
      events: 'click_keyboard',
      picOff: 'assets/images/keyboard_w.png',
      picOn: 'assets/images/keyboard_on.png',
      title: 'Keyboard',
      isFav: false,
      sounds: "assets/audio/keyboard.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      player: AssetsAudioPlayer()),
];

List<ViewModels> get models0 => arrays0;
final arrays0 = [
  ViewModels(
    isDarkMode: false,
  ),
];
