import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:good_dream/models/view_models.dart';

List<ViewModels> get models3 => arrays3;
final arrays3 = [
  ViewModels(
      disableIcon: 'assets/images/lotus_w.png',
      enableIcon: 'assets/images/lotus_on.png',
      iconTitleText: 'Meditation',
      audioFile: "assets/audio/flowing_river2.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/healing_w.png',
      enableIcon: 'assets/images/healing_on.png',
      iconTitleText: 'Healing meditation',
      audioFile: "assets/audio/healing_meditation.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/yoga_w.png',
      enableIcon: 'assets/images/yoga_on.png',
      iconTitleText: 'Yoga',
      audioFile: "assets/audio/morning_sun.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/piano3_w.png',
      enableIcon: 'assets/images/piano3_on.png',
      iconTitleText: 'Asian piano',
      audioFile: "assets/audio/asian_piano.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/piano6_w.png',
      enableIcon: 'assets/images/piano6_on.png',
      iconTitleText: 'Piano',
      audioFile: "assets/audio/love_piano.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/piano5_w.png',
      enableIcon: 'assets/images/piano5_on.png',
      iconTitleText: 'Background Piano ',
      audioFile: "assets/audio/background_piano.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/binaural_w.png',
      enableIcon: 'assets/images/binaural_on.png',
      iconTitleText: 'Binaural',
      audioFile: "assets/audio/binaural.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/guitar_w.png',
      enableIcon: 'assets/images/guitar_on.png',
      iconTitleText: 'Guitar Song',
      audioFile: "assets/audio/ambient_guitars.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/guitar_w.png',
      enableIcon: 'assets/images/guitar_on.png',
      iconTitleText: 'Background Guitar',
      audioFile: "assets/audio/background_guitar.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/om_w.png',
      enableIcon: 'assets/images/om_on.png',
      iconTitleText: 'Om surrounding',
      audioFile: "assets/audio/om.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/zen_w.png',
      enableIcon: 'assets/images/zen_on.png',
      iconTitleText: 'Zen',
      audioFile: "assets/audio/zen.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/flute_w.png',
      enableIcon: 'assets/images/flute_on.png',
      iconTitleText: 'Flute',
      audioFile: "assets/audio/flute.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
];

List<ViewModels> get models4 => arrays4;
final arrays4 = [
  ViewModels(
      checkThemeMode: null,
      disableIcon: 'assets/images/plane_w.png',
      enableIcon: 'assets/images/plane_on.png',
      iconTitleText: 'Plane',
      audioFile: "assets/audio/plane.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/train_w.png',
      enableIcon: 'assets/images/train_on.png',
      iconTitleText: 'Train',
      audioFile: "assets/audio/train.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/car_w.png',
      enableIcon: 'assets/images/car_on.png',
      iconTitleText: 'Car Driving',
      audioFile: "assets/audio/car_driving.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/bus_w.png',
      enableIcon: 'assets/images/bus_on.png',
      iconTitleText: 'Bus',
      audioFile: "assets/audio/fast_bus.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/washing_machine_w.png',
      enableIcon: 'assets/images/washing_machine_on.png',
      iconTitleText: 'Washing machine',
      audioFile: "assets/audio/washing_machine.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/air_conditioner_w.png',
      enableIcon: 'assets/images/air_conditioner_on.png',
      iconTitleText: 'Air Conditioner',
      audioFile: "assets/audio/air_conditioner2.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/vacuum_cleaner_w.png',
      enableIcon: 'assets/images/vacuum_cleaner_on.png',
      iconTitleText: 'Vacuum cleaner',
      audioFile: "assets/audio/vacuum_cleaner2.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/hair_dryer_w.png',
      enableIcon: 'assets/images/hair_dryer_on.png',
      iconTitleText: 'Hair dryer',
      audioFile: "assets/audio/hair_dryer2.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
  ViewModels(
      disableIcon: 'assets/images/keyboard_w.png',
      enableIcon: 'assets/images/keyboard_on.png',
      iconTitleText: 'Keyboard',
      audioFile: "assets/audio/keyboard.ogg",
      opacityOff: 0.0,
      opacityOn: 1.0,
      isFav: false,
      player: AssetsAudioPlayer()),
];

List<ViewModels> get models0 => arrays0;
final arrays0 = [
  ViewModels(
    isDarkMode: false,
  ),
];
